name: sample
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0+4

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_custom_tabs: ^1.0.4
  flutter_phone_direct_caller: ^2.1.1
  flutter_webview_plugin: ^0.4.0
  universal_html: ^2.2.3
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
