-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgpz2bahk1LqZA7P8q
Wb2YJeTZpg5e4bmrYjdxVQhndVugCgYIKoZIzj0DAQehRANCAASUhteYu9Id30hF
cOuDGrWVmm2CKvvuEP7SyFdca0Z0SkNo7pY9Tu0P7gPmtGpdAMm5HuPX6zgwNdbZ
nvYRCBLN
-----END PRIVATE KEY-----
