name: remote-config-deployer

on: [push]

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('packages/app_user/scripts/remote_config/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          cd packages/app_user/scripts/remote_config/
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt ; fi

      - name: Create service account key
        env:
          FB_SERVICE_ACCOUNT_BASE64: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAibWVkaWNhLXRlc3QiLAogICJwcml2YXRlX2tleV9pZCI6ICI0YWY3ZDhmZWFiZTFkOWVmNzNmZDczOTRjNjgwODU4ZmJjMDEzZDY0IiwKICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdkFJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLWXdnZ1NpQWdFQUFvSUJBUUNoajJlV2dzRXpQTFVZXG4vVS9OTnJRdUtDTmpyc3NGaFBoU3VOWURIVzlsMGFjS3BpcGgzSWROUkhnVTlWREEwREprM1ErbjBVRXhwZVJTXG5rNGsvUTA5MDZmMkE5MWZsWWMwUEpQVXhxRGppdlFZMVNYMWJ6Y1FyNFRKM0gvNStWaXYvcjMvbWxTUUIwK0N5XG40dUIvQ2FjQy9vcTBxSm1wbWlRanlNSkFSVlE0UVB3RGdQV1dSNEYyczM3aWxEaitjLzRqR0c0Wm5NMjBCNXVyXG42LzF6M1pUUWlBWklJRU9BdmtvZmU3VXZDTGpMVi9Na2lhajhqNExTUmhjOXloUm1VSVdsdktXNVpDVGllOU1kXG5hMWpvWHl0bGQvYTBWbmEyN0VqMVlSTjZ3ZE5vYVBtRElWZE5qUmVsbWRqdUpJais5WWVVbWNtOGpUQ0hSSkJ0XG5kN3phSHlIQkFnTUJBQUVDZ2dFQUcvTHNoeStvajU0VmNEVEdQT2lWUkJUaWhtaWpLNW5Fd2I3REd6Zlk0U0xqXG5SR2JabHlObzdyZUZGSThad0xsanRtbzl2cGpuTDlrVWhpcUt5RHh6UHZVSnkyayt0ZXAwNklWS3U2UHY3MTJtXG4rTW4xVzAvZCszOVNWU1JlU09uTVk4ZXZGeXMrMXVnYUM2aFBFUHNRL3VZZEJjTFREbkdoaGVWQm9ZKzgwWnc1XG5rMHdDRmZwb241bkNnbU54NU8rZ2pxT092ejBHdnJSdDBHdjZRVE43NjNnaWoycGN3Q2QvK0hjamhDd2F1STZ4XG5IVThEcCsyNTVOalpHQnZnNlhFdXNJb0xyM0MxdVE1cFFYQjNETEhmYmxOZVlFYmhsaXhvMjRocEtXaEN5RXV5XG5tTU53RG9LdkxxbUtZOWxveFV1Wnl3MUwvY1VObFpCSHk5NWNma2hpWndLQmdRRGk1dzRyUkF6TWpTMXlDOG5TXG5JQm9sZUJ4RmZVWXpyZWk3cjltMzlsUnNXM1VyWlZKMHkvTEtMTjVyRDNocWIwUmhxYlJJdUZtdTN1NGxwcGM5XG5hclhvSmlCZXV2dlB0dkhuK0J5WWtOVmxGY1VPT1VSV0xHMnNoRUhrV3NPRHZkK3VUeW53OVRVNGtORW1oV2dWXG43d1E3bVV4dEk5UEYwQ2Q0NjdVRHJsVHhmd0tCZ1FDMlJ6eEk5Z2tiaWF5b3k1ZU9oWWhGVnREUnE5Z3pGb3NvXG5GZlBpMjNDNVRCK3JJTlV2OVNkREJ5QTFXcUZNeG9KSS9LZG5jcnBEWkdWUzJzclFSUFBubEFkWXBzK2gySFB1XG5EOW9KTVVjNmowUVI2V0VYbkFGaDBIdHJNUk90eHkzdExsZmRoZTA3dXVrcWFhVFVBUzJkK2l2UmVBUW81R096XG4wd3Q2bnhNTXZ3S0JnRnAxNDZBOE1SNGI2dEpkQU1sVkl4ZHRHMWhZNlhRUkVZaENRM3FrS21SSTBoM0s5MlM1XG5Lc0tQd056Ti9pUHcyRUpYZGhqSDVubGhSM0NiU2hDaVNvT1RMN1NVdDIvSWNBa2JVY3RCY3RJcUs3WFAvdjZjXG5GOTEvblFWOWFoVkx6YkdndmdmaXVxVWlsei9VVC9ydW43RmpIS1VtYzNlWjFTTFFWZ3B4cGt2aEFvR0Fjcy9yXG42UWtRTTRoRWVRM0VLTUZ6VkRtYXpuYXZkMzU3cUlRcldubGVSMWpybVo3VXFhQ0JXbmJpa3JqRFlOaW90OUJzXG5vWHhpVnBDbVFjb09kYUQ1QUtUOCs1b1dycHJvYXNzUlN6ais1S1BZL0c5RCtOc0xBOUdONjdhOTduZkhOZDQ2XG4rZzJob0QzYklCdnE5cDdIWFBwM0h6bTVaUWgyeEkzcWJSSkZyWUVDZ1lBVUlUVDJaUzMyMGtGclJXa2I5Tml1XG5NL1VaQ1RsSzJpRTFNODgxVTQ3LzRQZXJKUEEyMVk3V3hKNGhoc3RGSEpBVWpNMXpMenFCRjlzK0l1amgrZ2RoXG5SNXdady85amM1TVcxanVpc0hWNzhDbEgzZ1ZCTVkwblI2d1g3ZHNJMHZuMWVOZTFDaDUwb3VocGtNNzFaS291XG5malNmOGxmS3hBRkxSK3J4QU9GRVNBPT1cbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsCiAgImNsaWVudF9lbWFpbCI6ICJmaXJlYmFzZS1hZG1pbnNkay1pbTI2bEBtZWRpY2EtdGVzdC5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsCiAgImNsaWVudF9pZCI6ICIxMDY4NDg5NDcwMjkyNjczMzQ2NDAiLAogICJhdXRoX3VyaSI6ICJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9vYXV0aDIvYXV0aCIsCiAgInRva2VuX3VyaSI6ICJodHRwczovL29hdXRoMi5nb29nbGVhcGlzLmNvbS90b2tlbiIsCiAgImF1dGhfcHJvdmlkZXJfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIvdjEvY2VydHMiLAogICJjbGllbnRfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9yb2JvdC92MS9tZXRhZGF0YS94NTA5L2ZpcmViYXNlLWFkbWluc2RrLWltMjZsJTQwbWVkaWNhLXRlc3QuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJ1bml2ZXJzZV9kb21haW4iOiAiZ29vZ2xlYXBpcy5jb20iCn0K
        run: |
          cd packages/app_user/scripts/remote_config/
          FILE_PATH=fb_credential.json
          echo -n "$FB_SERVICE_ACCOUNT_BASE64" | base64 --decode --output $FILE_PATH

      - name: Publish
        env:
          PROJECT_ID: medica-test
          CREDENTIALS: fb_credential.json
          PLATFORM_APP: ios
          VERSION_APP: 1.1.10.2
        run: |
          cd packages/app_user/scripts/remote_config/
          python config_manager.py --action=publish
