name: Call Firebase Cloud Messaging API

on:
  push:
    branches:
      - main

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make API Request
        run: |
          curl --location 'https://fcm.googleapis.com/fcm/send' \
          --header 'Authorization: key=AAAASw-TuVA:APA91bEcAgj8o_2vZ94CEdaoAQLiV6uk55eMxDcnhxWhM3l5tAr7G0-N92jqeQe3DYlhMcKYIq5rOkyXg5cVLROfm1QR9cwgKxV4vddmKS77FbXJis2jTo20pXwPWQpeppt8vM73p3WC' \
          --header 'Content-Type: application/json' \
          --data '{
              "registration_ids": [
                  "e_ZnqL1FTr2ICABltLU-iT:APA91bHEpjc41Y2FHXyXFAdVLYjDQGnqe4UUsWTmGj5-mnpqDcGsrIzH47wpMtGGbVxqmGOfK0NeQxzErG9Vw4FuHStvsYFseieljR1qqZQmg7GcgHnEsD3299bwQrdqIzrd-VUJd_Iy"
              ],
              "notification": {
                  "body": "tunglam bodyyyyyyyyyyyyyyyyy",
                  "title": "tunglam titleeeeeeeeeeeeeeeeeeee"
              },
              "data": {
                  "type": "kokoko",
                  "screen_name": "/notification",
                  "payload": {
                      "id": "cbudsbvsducbisbc"
                  }
              }
          }'
